### ISSUE TITLE
The example is wrong

### ISSUE THREAD

**Issue by GiuseppeCM** [apostrophecms/apostrophe-seo#21]
The example in README.md is wrong,
If you put the {% block title %}{{ title }}{% endblock %} in {% block extraHead %}, you will see the title on the page, and not in <title> element, beacause the <title> in your template (outerLayoutBase.html) it's out of the `extraHead` block.
I solve it in this way:
```
{% block title %}
             {% if data.piece %}
                {% if data.piece.seoTitle %}
                                {% set seoTitle = data.piece.seoTitle %}
                {% else %}
                                {% set seoTitle = data.piece.title %}
                {% endif %}
             {% else %}
                {% if data.page.seoTitle %}
                                {% set seoTitle = data.page.seoTitle %}
                {% else %}
                                {% set seoTitle = data.page.title %}
                {% endif %}
           {% endif %}
                {{seoTitle}}
{% endblock %}
{% block extraHead %}
                {% include "apostrophe-seo:view.html" %}
{% endblock %}
```

In `apostrophe-seo:view.html` the title is not used.

**Comment by abea** [comment]
Thanks, @GiuseppeCM. I think you're right. I'm submitting a PR to update the example to match how we actually tend to use it.
