### ISSUE TITLE
Canonical Link URLs are relative 

### ISSUE THREAD

**Issue by Eric-Dunaway** [apostrophecms/apostrophe-seo#42]
https://github.com/apostrophecms/apostrophe-seo/blob/116f642a524157d4687ef731ce495e4a4af10b8a/views/view.html#L23-L25

Google Lighthouse considers relative canonical links invalid.
![image](https://user-images.githubusercontent.com/36860672/94078327-639a7500-fdbb-11ea-9e0c-2db4ce804da1.png)

Link to the code for the canonical links audit
https://github.com/GoogleChrome/lighthouse/blob/478a954f85746b3b36cb09fc9132fcd870617973/lighthouse-core/audits/seo/canonical.js#L31-L35

**Comment by Eric-Dunaway** [comment]
Another reference https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html#:~:text=Mistake%202%3A%20Absolute%20URLs%20mistakenly%20written%20as%20relative%20URLs

**Comment by abea** [comment]
@Eric-Dunaway Do you have the `baseUrl` property set on the app? It's commonly set on the server in the `data/local.js` file.

**Comment by Eric-Dunaway** [comment]
@abea No I did not have that set but that does fix the issue.

Thanks for the help! 🙏
It might help the next person to add a note to the documentation for this module.
