### ISSUE TITLE
Enforce character limit for seoDescription and seoTitle

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe-seo#5]

**Comment by austinstarin** [comment]
According to Moz:

> Google typically displays the first 50–60 characters of a title tag. If you keep your titles under 60 characters, our research suggests that you can expect about 90% of your titles to display properly. There's no exact character limit, because characters can vary in width and Google's display titles max out (currently) at 600 pixels.

> Meta descriptions can be any length, but Google generally truncates snippets ~300 characters (this limit increased in December 2017). It's best to keep meta descriptions long enough that they're sufficiently descriptive, so we recommend descriptions between 50–300 characters. Keep in mind that the "optimal" length will vary depending on the situation, and your primary goal should be to provide value and drive clicks.


It would be nice to provide user feedback on the length of the text provided with a character limit enforced.

**Comment by woodbrearlham** [comment]
Can't this issue be closed?

**Comment by abea** [comment]
yep!
