### ISSUE TITLE
Add field for Google Analytics to global configuration

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe-seo#6]

**Comment by austinstarin** [comment]
@bgantick @arti5m should we give a field for this if you configure it or even automatically in `apostrophe-global`? Too much?

**Comment by boutell** [comment]
Google Analytics is not SEO, per se, so I have concerns about adding it to what could become a kitchen sink module if we keep going down that road...

**Comment by austinstarin** [comment]
That's fine. WordPress's Yoast does all these things so it's a consideration.

**Comment by boutell** [comment]
Ah! I think Yoast parity is a good argument and we should do it. If they have a good working definition of "SEO and similar stuff that if you don't do it you look like a dummyhead" then we should piggyback on that.
