### ISSUE TITLE
Should the Title and Description fields be required by default?

### ISSUE THREAD

**Issue by arti5m** [apostrophecms/apostrophe-seo#8]

**Comment by austinstarin** [comment]
@arti5m @bgantick I think this could be fine and we could allow to configure this easily. Maybe by default it's not required, but there's a required option at the top level that makes the fields required for every doctype subclass.

**Comment by austinstarin** [comment]
@bgantick @arti5m @abea @mtthwmnc @boutell Any strong feelings on this?

**Comment by bgantick** [comment]
My vote would be for "no", as crawlers will try to infer if meta tags aren't present on a page.

**Comment by abea** [comment]
My b.

**Comment by austinstarin** [comment]
Thanks @bgantick.
